In [53]:
import numpy as np

In [204]:
#1
arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
def only0dd(arr):
    for row in range(len(arr)):
        if np.sum(arr[row] %2) == 3:
            print(arr[row])
only0dd(arr)

[5 7 9]
[7 7 7]


In [205]:
#2.1
checkerboard = np.zeros((8, 8))
print(checkerboard)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [206]:
#2.2
checkerboard[0::2, 0::2] = "1"
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [207]:
#2.3
checkerboard[1::2, 1::2] = "1"
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [208]:
#2.4
checkerboard_flipped = np.zeros((8,8))
checkerboard_flipped[0::2, 1::2] = "1"
checkerboard_flipped[1::2, 0::2] = "1"
print(checkerboard_flipped)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [209]:
#3
def expansion(array, x):
    universe = np.array(["galaxy", "clusters"])
    space = x*' '
    new_universe = []
    for word in universe:
        new_word = (list(word))
        new_word = (space.join(list(word)))
        new_universe.append(new_word)
    return new_universe
print(expansion(universe, 6))

['g      a      l      a      x      y', 'c      l      u      s      t      e      r      s']


In [210]:
def second_largest():
    planets = np.random.randint(100, 1000, (5, 5))
    print(planets)
    
    second_max = []
    
    for i in range(planets.shape[1]):
        column = planets[:, i]
        sorted_column = sorted(list(column))[::-1]
        for num in column:
            second = sorted_column[1]
        second_max.append(second)
    return second_max
print("second_largest =", second_largest())

[[745 579 374 368 513]
 [122 411 532 712 970]
 [404 472 936 576 177]
 [603 858 336 294 616]
 [703 632 261 273 993]]
second_largest = [703, 632, 532, 576, 970]
